### ISSUE TITLE
[Bug] Different CLI version when using `go install`

### ISSUE THREAD

**Issue by valentimarco** [saniales/meow#3]
When using  `go install github.com/saniales/meow-cli` to install the cli, the version displayed is different from the version created when using ` make cross-compile`.
![image](https://github.com/saniales/meow-cli/assets/26926690/1651b2fd-903d-4abb-9d83-d8ac1d060e5f)

**Describe the solution you'd like**
@saniales thought about using Tags + commit versioning to resolve the issue, obtainable by `git describe --tags`. 
In addiction, I propose a github action for releases with the new versioning. [Here an example from another cli](https://github.com/cosmtrek/air/blob/master/.github/workflows/release.yml)

**Comment by valentimarco** [comment]
The `go install` method can be usuful to build [PKGBUILDS](https://wiki.archlinux.org/title/PKGBUILD) and include the mewo cli to the AUR (Arch User Repository)

**Comment by saniales** [comment]
Now go install shows (devel) in version, as it's directly built from source
